<?php

namespace App\Http\Controllers;

use App\Exports\StockReportExport;
use App\Models\Product;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Maatwebsite\Excel\Facades\Excel;

class StockController extends Controller
{
    public function index()
    {
        $products = Product::where('is_active', true)->get();

        return view('reports.stock', compact('products'));
    }

    public function export()
    {
        $stockExpression = 'products.opening_stock_units + COALESCE(SUM(CASE
            WHEN stock_transactions.type = "purchase" THEN stock_transactions.quantity_in_units
            WHEN stock_transactions.type = "sale" THEN -stock_transactions.quantity_in_units
            WHEN stock_transactions.type = "adjustment" THEN stock_transactions.quantity_in_units
            ELSE 0 END), 0)';

        $rows = DB::table('products')
            ->leftJoin('stock_transactions', 'products.id', '=', 'stock_transactions.product_id')
            ->where('products.is_active', true)
            ->whereNull('products.deleted_at')
            ->groupBy('products.id', 'products.name', 'products.volume', 'products.product_code', 'products.pack_size', 'products.opening_stock_units', 'products.trade_price')
            ->select('products.id', 'products.name', 'products.volume', 'products.product_code', 'products.pack_size', 'products.trade_price')
            ->selectRaw("($stockExpression) as current_units")
            ->orderBy('products.name')
            ->orderBy('products.id')
            ->get();

        $tableRows = [];
        $totalUnitsAll = 0;
        $totalAmountAll = 0.0;
        foreach ($rows as $i => $r) {
            $pack = (int) ($r->pack_size ?? 1);
            if ($pack <= 0) $pack = 1;
            $units = (int) ($r->current_units ?? 0);
            $ct = (int) floor($units / $pack);
            $un = (int) ($units % $pack);
            $lineAmount = (float) $units * (float) ($r->trade_price ?? 0);

            $status = 'In Stock';
            if ($units <= 0) {
                $status = 'Out of Stock';
            } elseif ($ct < 5) {
                $status = 'Low Stock';
            }

            $productName = trim((string) ($r->name ?? '') . ((string) ($r->volume ?? '') !== '' ? ' ' . (string) $r->volume : ''));

            $tableRows[] = [
                $i + 1,
                $productName !== '' ? $productName : '-',
                (string) ($r->product_code ?? '') !== '' ? (string) $r->product_code : '-',
                $ct . ' / ' . $un,
                $units,
                $lineAmount,
                $status,
            ];

            $totalUnitsAll += $units;
            $totalAmountAll += $lineAmount;
        }

        $tableRows[] = ['', 'Total', '', '', $totalUnitsAll, $totalAmountAll, ''];

        $headings = [
            'Sr No.',
            'Product Name',
            'Product Code',
            'Current Stock (CT/UN)',
            'Total Units',
            'Total Amount ₹',
            'Status',
        ];

        $user = Auth::user();
        $generatedBy = $user ? (trim((string) ($user->name ?? '')) !== '' ? (string) $user->name : (string) ($user->email ?? '')) : '';
        $now = now();
        $meta = [
            'company' => 'SAGARDUTT PEPSI DISTRIBUTORS',
            'report' => 'Stock Report',
            'date_range' => 'Date: ' . $now->toDateString(),
            'generated_line' => 'Generated On Date: ' . $now->toDateString() . '   Generated Time: ' . $now->format('H:i:s') . '   Generated By: ' . $generatedBy,
        ];

        $qtyCols = [1, 5];
        $currencyCols = [6];
        $productNameCol = 2;
        $file = 'stock-report_' . $now->format('Ymd_His') . '.xlsx';

        return Excel::download(new StockReportExport($tableRows, $headings, $meta, $qtyCols, $currencyCols, $productNameCol), $file);
    }
}
